# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: 339713089664.dkr.ecr.ap-south-1.amazonaws.com/cicd-eks:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
