# .github/workflows/deploy.yml

name: Deploy NGINX to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    


    - name: Authenticate with ECR
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cicd-eks:latest .
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cicd-eks:latest

    - name: Authenticate with ECR
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Install kubectl
      run: |
        sudo apt-get update
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mkdir -p $HOME/bin && mv ./kubectl $HOME/bin/kubectl
        echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc
        kubectl version --client
        aws --version

    - name: Update kube config
      run: aws eks update-kubeconfig --name eks-task --region ap-south-1

    - name: Deploy to Kubernetes
      run: |
        aws configure list
        kubectl config view
        kubectl config current-context
        kubectl get nodes -A -o wide
        
