# .github/workflows/deploy.yml

name: Deploy NGINX to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build and Push Docker Image to ECR
      run: |
        # Authenticate Docker with ECR
        aws ecr get-login-password --region ap-south-1 ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

        # Build NGINX Docker image
        docker build -t ${{ secrets.AWS_ECR_REGISTRY }}/cicd-eks .

        # Tag the Docker image
        docker tag ${{ secrets.AWS_ECR_REGISTRY }}/cicd:latest ${{ secrets.AWS_ECR_REGISTRY }}/cicd-eks:latest

        # Push the Docker image to ECR
        docker push ${{ secrets.AWS_ECR_REGISTRY }}/cicd-eks:latest

    - name: Configure kubectl
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
