# .github/workflows/deploy.yml

name: Deploy NGINX to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Assume IAM role
      run: |
        aws sts assume-role --role-arn arn:aws:iam::339713089664:role/ec2-eks-role --role-session-name GitHubActionsSession > assumed-role.json
        export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId assumed-role.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey assumed-role.json)
        export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken assumed-role.json)
      env:
        AWS_DEFAULT_REGION: ap-south-1
        AWS_DEFAULT_OUTPUT: json


    - name: Authenticate with ECR
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cicd-eks:latest .
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cicd-eks:latest

    - name: aws version check
      run: |
        aws --version

    - name: Authenticate with EKS
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name eks-task
        aws eks --region ${{ secrets.AWS_REGION }} get-token --cluster-name eks-task > ~/.kube/token
      shell: bash

    - name: Check Kubernetes cluster status
      run: kubectl cluster-info dump

    - name: Deploy to Kubernetes
      run: |
        kubectl cluster-info
        kubectl get pods -A
        
  
